// Central product catalog for Colors Dress.
// Product images use LoremFlickr — real, keyword-matched photos from Flickr
// under Creative Commons. Each image is pinned with a `lock` seed so the same
// product always shows the same photo. Swap these for your own product photos
// (drop files in /public/products and use "/products/<file>.jpg") for launch.

const flick = (tag, lock) => `https://loremflickr.com/600/800/${tag}?lock=${lock}`;
const flickSq = (tag, lock) => `https://loremflickr.com/600/600/${tag}?lock=${lock}`;

export const categories = [
  { slug: "dresses", name: "Dresses", tagline: "Kurtis, Gowns & more", image: flickSq("dress", 101) },
  { slug: "inners-lingerie", name: "Inners & Lingerie", tagline: "Bra, Panties & more", image: flickSq("clothing", 102) },
  { slug: "bottoms", name: "Bottoms", tagline: "Leggings, Pants & more", image: flickSq("jeans", 103) },
  { slug: "accessories", name: "Accessories", tagline: "Bags, Jewellery & more", image: flickSq("handbag", 104) },
  { slug: "all-stock", name: "All Stock", tagline: "Explore Everything", image: flickSq("boutique", 105) },
];

export const products = [
  {
    slug: "floral-printed-kurti",
    name: "Floral Printed Kurti",
    category: "dresses",
    price: 699,
    mrp: 1299,
    rating: 4.4,
    ratingCount: 512,
    colors: ["#F48FB1", "#E57373", "#F5CBA7", "#90A4AE", "#B0BEC5"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [flick("dress", 201), flick("fashion", 202), flick("gown", 203)],
    fabric: "100% Cotton",
    description:
      "Flared floral printed kurti in pure cotton with a beautiful print. Perfect for casual and festive occasions.",
    details: ["Fabric: 100% Cotton", "Sleeve: 3/4th Sleeve", "Pattern: Floral Print", "Neck: Round Neck"],
    bestseller: true,
  },
  {
    slug: "embroidered-anarkali-gown",
    name: "Embroidered Anarkali Gown",
    category: "dresses",
    price: 1299,
    mrp: 2499,
    rating: 4.6,
    ratingCount: 340,
    colors: ["#8E24AA", "#5E35B1", "#C2185B"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("gown", 204), flick("dress", 205), flick("fashion", 206)],
    fabric: "Georgette",
    description:
      "Floor-length embroidered Anarkali gown with intricate thread work. A stunning pick for weddings and parties.",
    details: ["Fabric: Georgette", "Sleeve: Full Sleeve", "Pattern: Embroidered", "Length: Floor Length"],
    bestseller: true,
  },
  {
    slug: "party-wear-frock",
    name: "Party Wear Frock",
    category: "dresses",
    price: 899,
    mrp: 1599,
    rating: 4.3,
    ratingCount: 210,
    colors: ["#EC407A", "#AB47BC", "#26A69A"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("dress", 207), flick("model", 208), flick("fashion", 209)],
    fabric: "Crepe",
    description: "Flowy party wear frock with a flattering silhouette, ideal for evening celebrations.",
    details: ["Fabric: Crepe", "Sleeve: Sleeveless", "Pattern: Solid", "Fit: Flared"],
  },
  {
    slug: "cotton-anarkali-kurti",
    name: "Cotton Anarkali Kurti",
    category: "dresses",
    price: 799,
    mrp: 1499,
    rating: 4.2,
    ratingCount: 178,
    colors: ["#FBC02D", "#F57C00", "#7CB342"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [flick("kurti", 210), flick("dress", 211), flick("fashion", 212)],
    fabric: "Cotton Blend",
    description: "Everyday cotton Anarkali kurti that keeps you comfortable and stylish all day.",
    details: ["Fabric: Cotton Blend", "Sleeve: 3/4th Sleeve", "Pattern: Printed", "Fit: Anarkali"],
  },
  {
    slug: "floral-maxi-dress",
    name: "Floral Maxi Dress",
    category: "dresses",
    price: 999,
    mrp: 1899,
    rating: 4.5,
    ratingCount: 289,
    colors: ["#F06292", "#4DB6AC", "#FF8A65"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("dress", 213), flick("summer", 214), flick("fashion", 215)],
    fabric: "Rayon",
    description: "Breezy floral maxi dress with a relaxed fit — perfect for brunches and vacations.",
    details: ["Fabric: Rayon", "Sleeve: Short Sleeve", "Pattern: Floral", "Length: Ankle Length"],
    bestseller: true,
  },
  {
    slug: "printed-a-line-frock",
    name: "Printed A-Line Frock",
    category: "dresses",
    price: 599,
    mrp: 1099,
    rating: 4.1,
    ratingCount: 143,
    colors: ["#BA68C8", "#4FC3F7", "#AED581"],
    sizes: ["S", "M", "L"],
    images: [flick("dress", 216), flick("fashion", 217), flick("model", 218)],
    fabric: "Cotton",
    description: "A-line printed frock with side pockets, a wardrobe essential for casual days.",
    details: ["Fabric: Cotton", "Sleeve: Sleeveless", "Pattern: Geometric Print", "Fit: A-Line"],
  },
  {
    slug: "seamless-everyday-bra",
    name: "Seamless Everyday Bra",
    category: "inners-lingerie",
    price: 499,
    mrp: 799,
    rating: 4.4,
    ratingCount: 621,
    colors: ["#E0C9A6", "#212121", "#FFFFFF"],
    sizes: ["32B", "34B", "36B", "38C"],
    images: [flick("clothing", 219), flick("textile", 220), flick("cotton", 221)],
    fabric: "Nylon Spandex",
    description: "Wire-free seamless bra with soft padded cups for all-day comfort under any outfit.",
    details: ["Fabric: Nylon Spandex", "Type: Seamless", "Padding: Lightly Padded", "Wire: Wire-Free"],
    bestseller: true,
  },
  {
    slug: "cotton-panty-pack",
    name: "Cotton Panty (Pack of 3)",
    category: "inners-lingerie",
    price: 399,
    mrp: 699,
    rating: 4.3,
    ratingCount: 455,
    colors: ["#F8BBD0", "#B39DDB", "#FFF59D"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("cotton", 222), flick("clothing", 223), flick("textile", 224)],
    fabric: "Cotton",
    description: "Breathable cotton hipster panties in a value pack of three soft everyday colours.",
    details: ["Fabric: Cotton", "Pack: 3 Pieces", "Rise: Mid Rise", "Style: Hipster"],
  },
  {
    slug: "satin-nightwear-set",
    name: "Satin Nightwear Set",
    category: "inners-lingerie",
    price: 899,
    mrp: 1699,
    rating: 4.5,
    ratingCount: 312,
    colors: ["#CE93D8", "#F48FB1", "#80CBC4"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("pajamas", 225), flick("clothing", 226), flick("silk", 227)],
    fabric: "Satin",
    description: "Smooth satin nightwear set — a top and shorts combo for a comfortable, luxurious sleep.",
    details: ["Fabric: Satin", "Set: Top + Shorts", "Pattern: Solid", "Care: Machine Wash"],
    bestseller: true,
  },
  {
    slug: "camisole-slip",
    name: "Camisole Slip",
    category: "inners-lingerie",
    price: 299,
    mrp: 549,
    rating: 4.2,
    ratingCount: 198,
    colors: ["#EEEEEE", "#212121", "#E0C9A6"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("clothing", 228), flick("cotton", 229), flick("textile", 230)],
    fabric: "Modal",
    description: "Soft modal camisole slip that layers smoothly under kurtis and sheer tops.",
    details: ["Fabric: Modal", "Strap: Adjustable", "Style: Camisole", "Fit: Regular"],
  },
  {
    slug: "cotton-leggings",
    name: "Cotton Leggings",
    category: "bottoms",
    price: 399,
    mrp: 599,
    rating: 4.4,
    ratingCount: 733,
    colors: ["#212121", "#5D4037", "#455A64", "#C2185B"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [flick("leggings", 231), flick("clothing", 232), flick("fashion", 233)],
    fabric: "Cotton Lycra",
    description: "Ankle-length cotton lycra leggings with a wide comfort waistband. Pairs with every kurti.",
    details: ["Fabric: Cotton Lycra", "Length: Ankle Length", "Waist: Elasticated", "Fit: Skinny"],
    bestseller: true,
  },
  {
    slug: "palazzo-pants",
    name: "Printed Palazzo Pants",
    category: "bottoms",
    price: 599,
    mrp: 1099,
    rating: 4.3,
    ratingCount: 267,
    colors: ["#7E57C2", "#26A69A", "#EF5350"],
    sizes: ["S", "M", "L", "XL"],
    images: [flick("trousers", 234), flick("fashion", 235), flick("clothing", 236)],
    fabric: "Rayon",
    description: "Flowy printed palazzo pants with a comfortable elastic waist — effortless everyday style.",
    details: ["Fabric: Rayon", "Length: Full Length", "Waist: Elasticated", "Fit: Wide Leg"],
  },
  {
    slug: "denim-jeggings",
    name: "Denim Jeggings",
    category: "bottoms",
    price: 799,
    mrp: 1499,
    rating: 4.2,
    ratingCount: 189,
    colors: ["#1565C0", "#212121", "#455A64"],
    sizes: ["28", "30", "32", "34", "36"],
    images: [flick("jeans", 237), flick("denim", 238), flick("fashion", 239)],
    fabric: "Denim Stretch",
    description: "Stretchable denim jeggings that give a jeans look with legging comfort.",
    details: ["Fabric: Denim Stretch", "Length: Ankle", "Rise: Mid Rise", "Fit: Skinny"],
  },
  {
    slug: "tote-handbag",
    name: "Structured Tote Handbag",
    category: "accessories",
    price: 899,
    mrp: 1999,
    rating: 4.5,
    ratingCount: 421,
    colors: ["#8D6E63", "#212121", "#C2185B"],
    sizes: ["Free"],
    images: [flick("handbag", 240), flick("bag", 241), flick("leather", 242)],
    fabric: "Faux Leather",
    description: "Roomy structured tote in premium faux leather — carries your day from work to weekend.",
    details: ["Material: Faux Leather", "Compartments: 2", "Closure: Zip", "Strap: Dual Handle"],
    bestseller: true,
  },
  {
    slug: "jhumka-earrings",
    name: "Oxidized Jhumka Earrings",
    category: "accessories",
    price: 249,
    mrp: 599,
    rating: 4.4,
    ratingCount: 356,
    colors: ["#B0BEC5", "#FFD54F"],
    sizes: ["Free"],
    images: [flick("earrings", 243), flick("jewelry", 244), flick("jewellery", 245)],
    fabric: "Alloy",
    description: "Traditional oxidized silver-tone jhumka earrings that elevate ethnic and fusion looks.",
    details: ["Material: Alloy", "Finish: Oxidized", "Type: Jhumka", "Closure: Push Back"],
  },
  {
    slug: "silk-scarf",
    name: "Printed Silk Scarf",
    category: "accessories",
    price: 349,
    mrp: 799,
    rating: 4.1,
    ratingCount: 98,
    colors: ["#EC407A", "#26C6DA", "#FFA726"],
    sizes: ["Free"],
    images: [flick("scarf", 246), flick("silk", 247), flick("fashion", 248)],
    fabric: "Satin Silk",
    description: "Lightweight printed silk scarf that adds a pop of colour to any outfit.",
    details: ["Material: Satin Silk", "Shape: Square", "Pattern: Printed", "Care: Hand Wash"],
  },
];

export function getProduct(slug) {
  return products.find((p) => p.slug === slug);
}

export function getByCategory(slug) {
  if (!slug || slug === "all-stock") return products;
  return products.filter((p) => p.category === slug);
}

export function discountPct(p) {
  return Math.round(((p.mrp - p.price) / p.mrp) * 100);
}

export function categoryName(slug) {
  return categories.find((c) => c.slug === slug)?.name || "All Stock";
}
